#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Update companion files generated by showinf -omexml-only, replacing the
# MetadataOnly elements by TiffData elements


import xml.etree.ElementTree as ElementTree
import re
import uuid
import string


NS = {'OME': "http://www.openmicroscopy.org/Schemas/OME/2016-06"}
NAME_PATTERN = re.compile("Well ([A-Z])-(\d+); Field #(\d)")
ElementTree.register_namespace("", NS['OME'])

companion_file = 'screenA/companions/Sac6-tdTomato_1.companion.ome'
tree = ElementTree.parse(companion_file)
root = tree.getroot()
well_uuids = {}

for i in root.findall('OME:Image', NS):
    name = i.attrib['Name']
    # Parse the image name and retrieve row/column/field
    m = NAME_PATTERN.match(name)
    row = string.ascii_uppercase.index(m.group(1))
    column = int(m.group(2)) - 1
    field = int(m.group(3)) - 1

    for p in i.findall('OME:Pixels', NS):
        # Dimension sanity check
        assert int(p.attrib['SizeC']) == 3
        assert int(p.attrib['SizeT']) == 1
        assert int(p.attrib['SizeZ']) == 5
        assert p.attrib['DimensionOrder'] == 'XYCZT'

        # Find the metadataonly element
        c = p.find('OME:MetadataOnly', NS)
        tail = c.tail
        index = list(p).index(c)

        # Determine field filename/UUID
        well_filename = "Sac6-tdTomato/1/%03d%03d000.flex" % (
            row + 1, column + 1)
        well_uuid = well_uuids.setdefault(well_filename, uuid.uuid4().urn)

        # Create a TiffData/UUID element
        field_tiffdata = ElementTree.Element(
            'TiffData', FirstC='0', FirstT='0', FirstZ='0', PlaneCount='15',
            IFD=str(field * 15))
        field_tiffdata.tail = tail
        field_uuid = ElementTree.SubElement(
            field_tiffdata, "UUID", {'FileName': well_filename})
        field_uuid.text = well_uuid
        field_uuid.tail = tail

        # Replace MetadataOnly element by TiffData
        p.remove(c)
        p.insert(index, field_tiffdata)

# Rewrite companion file
tree.write(companion_file, encoding='UTF-8', xml_declaration=True)
